spring:
  config:
    import:
      - classpath:/application-secret.yml
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            scope: email
            redirect-uri: http://sixman-front-s3.s3-website.ap-northeast-2.amazonaws.com
          github:
            scope: user:email, read:user
            redirect-uri: http://sixman-front-s3.s3-website.ap-northeast-2.amazonaws.com
          kakao:
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
            redirect-uri: http://sixman-front-s3.s3-website.ap-northeast-2.amazonaws.com
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  access-token-expire-time: 72000000
  refresh-token-expire-time: 604800000

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sixman-rds.c2bhjqsi4ogs.ap-northeast-2.rds.amazonaws.com/sixmandb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
url:
  frontend: http://sixman-front-s3.s3-website.ap-northeast-2.amazonaws.com
server:
  port: 80

---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
            google:
                redirect-uri: http://localhost:3000
            github:
                redirect-uri: http://localhost:3000
            kakao:
                redirect-uri: http://localhost:3000
url:
  frontend: http://localhost:3000